baseURL = 'https://example.org/'
languageCode = 'en-us'
title = ''
theme = 'hugo-theme-nix'

[params]
  Name = "Hello, I'm Miko≈Çaj"
  HeaderUsername = "xRezek"
  HeaderHostname = "maj"
  About = "Laravel / DevOps Solutions Developer from Poland."

  Email = "mikolaj.maj22@gmail.com"
  GithubID = "xRezek"

[menu]
  [[menu.header]]
    name = "projects"
    weight = 0
    url = "/projects"