baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'hugo-theme-nix'

[params]
  Name = "Hello, I'm Miko≈Çaj"
  HeaderUsername = "username"
  HeaderHostname = "hostname"
  About = "info_about_you"
  ProfilePicture = "profile_picture_url"